//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyamNyamWebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientOfStage
    {
        public int CookingStageId { get; set; }
        public int IngredientId { get; set; }
        public double Quantity { get; set; }
    
        public virtual CookingStage CookingStage { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
